[package]
name = "nano-hat-oled-armbian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2cdev = "0.5"
libc = "0.2"
embedded-graphics = "0.8.0"
ttf-parser = "0.19.0"